export const LAYOUT = {
  DEFAULT_LAYOUT: 'DEFAULT_LAYOUT',
  ERROR_LAYOUT: 'ERROR_LAYOUT',
  SINGLE_DIALOG_LAYOUT: 'SINGLE_DIALOG_LAYOUT',
  FULLSCREEN_LAYOUT: 'FULLSCREEN_LAYOUT',
}
export const TEST_TYPE = {
  QUIZ: 'QUIZ',
  MID_TERM_TEST: 'MID TERM TEST',
  FINAL_TEST: 'FINAL TEST',
  MOCK_TEST: 'MOCK TEST',
  ENTRANCE_TEST: 'ENTRANCE TEST',
  // STORY = 'STORY',
  TOPIC_TEST: 'TOPIC TEST',
  CHAPTER_TEST: 'CHAPTER TEST',
} as any
