default:
  image: node:16.17.0-alpine

deploy_prod:
  stage: deploy
  only:
    - master
  script:
    - yarn global add vercel
    - yarn install
    - VERCEL_TOKEN=$VERCEL_TOKEN_PROD && VERCEL_ORG_ID=$VERCEL_ORG_ID_PROD && VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_PROD && vercel deploy --prod --token=$VERCEL_TOKEN
  environment: production
