default:
  image: node:16.17.0-alpine

deploy_prod:
  stage: deploy
  only:
    - master
  script:
    - yarn global add vercel
    - yarn install
    - vercel deploy --prod --token=$VERCEL_TOKEN
  environment: production
