version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: aht.dev.Dockerfile

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - ${NEXT_APP_EXTERNAL_PORT:-3080}:3000
    logging:
      options:
        max-size: '10m'
        max-file: 3
