version: '3'

services:
  next-app:
    container_name: lms-app
    build:
      context: ./
      dockerfile: prod.Dockerfile
      # args:
      #   NEXTAUTH_URL: ${NEXTAUTH_URL}
      #   NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    restart: always
    ports:
      - ${EXPOSE_PORT}:${PORT}
    environment:
      REACT_APP_API_PUBLIC: ${REACT_APP_API_PUBLIC}
    networks:
      - my_network
    
networks:
  my_network:
    driver: bridge
        
