packages:
  - apps/lms-pro
  - apps/lms-zoom
  - apps/lms-test
  # - apps/lms-finhub  # tạm tắt, không dùng
  - features/*
  - libs/*
  - tools/*

hoistPattern:
  - react*
  - antd
  - '@ant-design/*'
