import { RouteGuard } from '@components/auth/RouteGuard'
import SappConfirmDialogContainer from '@components/base/confirm-dialog/SappConfirmDialogContainer'
import Layout from '@components/layout'
import SingleDialogLayout from '@components/layout/SingleDialog'
import '@styles/globals.scss'
import { LAYOUT } from '@utils/constants'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Toaster } from 'react-hot-toast'
import { injectStore } from 'src/redux/services/httpService'
import { store, wrapper } from '../redux/store'
import FullScreenLayout from '@components/layout/FullScreenLayout'
import { useEffect, useState } from 'react'
import { useAppDispatch, useAppSelector } from 'src/redux/hook'
import { onMessageListener } from 'src/utils/firebase'
import {
  showNotification,
  hideNotification,
} from 'src/redux/slice/Notification/Notification'
import { useRouter } from 'next/router'
import LearningResource from '@components/mycourses/LearningResource'
import { getCountUnRead } from 'src/redux/slice/Notification/Notification'
import AsyncStorage from '@react-native-async-storage/async-storage'
import LearningNotesList from '@components/mycourses/LearningNotesList'

// import 'antd/dist/antd.css'

type MyAppProps = AppProps & {
  Component: {
    layout?: String
  }
}

function MyApp({ Component, pageProps }: MyAppProps) {
  let content = null
  const { layout = LAYOUT.DEFAULT_LAYOUT } = (Component as any) || {}
  injectStore(store)
  const [show, setShow] = useState(false)
  const router = useRouter()
  const [openResource, setOpenResource] = useState(false)

  const dispatch = useAppDispatch()
  const getNotiUnread = useAppSelector(
    (state) => state.notificationReducer?.total_records,
  )

  const coutNotificationsUnRead = async () => {
    const accessToken = await AsyncStorage.getItem('accessToken')
    if (accessToken) {
      try {
        await dispatch(getCountUnRead())
      } catch (error) {}
    }
  }

  useEffect(() => {
    onMessageListener().then((data: any) => {
      dispatch(showNotification())
    })

    // Đếm số lượng noti chưa đọc, nếu lớn hơn 0 thì hiển thị thông báo
    coutNotificationsUnRead()
    if (getNotiUnread > 0) {
      dispatch(showNotification())
    } else {
      dispatch(hideNotification())
    }
  })

  switch (layout) {
    case LAYOUT.ERROR_LAYOUT:
      content = <Component {...pageProps} />
      break
    case LAYOUT.SINGLE_DIALOG_LAYOUT:
      content = (
        <SingleDialogLayout>
          <Component {...pageProps} />
        </SingleDialogLayout>
      )
      break
    case LAYOUT.FULLSCREEN_LAYOUT:
      content = (
        <FullScreenLayout>
          <Component {...pageProps} />
        </FullScreenLayout>
      )
      break
    default:
      content = (
        <Layout openDrawer={openResource} setOpenResource={setOpenResource}>
          <Component {...pageProps} />
        </Layout>
      )
  }

  useEffect(() => {
    if (typeof window !== 'undefined') {
      if (window.localStorage.getItem('accessToken') === '') {
        setOpenResource(false)
      }
    }
  }, [router.pathname])

  return (
    <>
      <Head>
        <title>LMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Toaster />
        <SappConfirmDialogContainer />
        <RouteGuard>
          <>
            {content}
            <LearningResource
              open={openResource}
              setOpenResource={setOpenResource}
            />
            <LearningNotesList />
          </>
        </RouteGuard>
      </main>
    </>
  )
}

export default wrapper.withRedux(MyApp)
