import Layout from '@components/layout'
import SingleDialogLayout from '@components/layout/SingleDialog'
import '@styles/globals.scss'
import { LAYOUT } from '@utils/constants'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { store, wrapper } from '../redux/store'
import { injectStore } from 'src/redux/services/httpService'

type MyAppProps = AppProps & {
  Component: {
    layout?: String
  }
}

function MyApp({ Component, pageProps }: MyAppProps) {
  let content = null
  const { layout = LAYOUT.DEFAULT_LAYOUT } = (Component as any) || {}
  injectStore(store)

  switch (layout) {
    case LAYOUT.ERROR_LAYOUT:
      content = <Component {...pageProps} />
      break
    case LAYOUT.SINGLE_DIALOG_LAYOUT:
      content = (
        <SingleDialogLayout>
          <Component {...pageProps} />
        </SingleDialogLayout>
      )
      break
    default:
      content = (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      )
  }

  return (
    <>
      <Head>
        <title>LMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{content}</main>
    </>
  )
}

export default wrapper.withRedux(MyApp)
