import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
            rel="stylesheet"
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
            function allowDrop(ev) {
              const slotId = ev.target.id
              const slotElement = document.getElementById(slotId)
              if (slotElement?.children.length > 0 || !ev.target.classList.contains("dropable")) {
                return
              } else{
                ev.preventDefault();
              }
            }

            function drag(ev) {
              ev.dataTransfer.setData("text", ev.target.id);
            }

            function drop(ev) {
              ev.preventDefault();
              var data = ev.dataTransfer.getData('text')
              ev.target.appendChild(document.getElementById(data))
            }
          `,
            }}
          />
        </Head>
        <body>
          <img
            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBg+A8AAQQBAHAgZQsAAAAASUVORK5CYII="
            alt="LMS FCP"
            width={1}
            height={1}
            style={{
              pointerEvents: 'none',
              position: 'absolute',
              top: `0`,
              zIndex: -1,
            }}
          />
          <img
            src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHdpZHRoPSI5OTk5OXB4IiBoZWlnaHQ9Ijk5OTk5cHgiIHZpZXdCb3g9IjAgMCA5OTk5OSA5OTk5OSIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj48ZyBzdHJva2U9Im5vbmUiIGZpbGw9Im5vbmUiIGZpbGwtb3BhY2l0eT0iMCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9Ijk5OTk5IiBoZWlnaHQ9Ijk5OTk5Ij48L3JlY3Q+IDwvZz4gPC9zdmc+"
            alt="LMS LCP"
            width="99999"
            height="99999"
            style={{
              pointerEvents: 'none',
              position: 'absolute',
              top: `0`,
              width: `calc(95vw)`,
              height: `calc(90vh)`,
              maxWidth: `calc(100vw)`,
              maxHeight: `calc(90vh)`,
              zIndex: -1,
            }}
          ></img>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
