export const PageLink = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_NEW: '/courses/new-courses',
  TOPICS: '/topics',
  CASE_STUDY: '/casestudy',
  TEACHERS: '/teachers',
  STUDENTS: '/students',
  TEACHER_MY_CLASS: '/teachers/my-class',
  TEACHER_MY_COURSE: '/teachers/courses',
  TEACHER_MY_REQUEST: '/teachers/my-request',
  TEACHER_CHAPTER_TEST: '/teachers/my-class/chapter-test',
  TEACHER_CASE_STUDY: '/teachers/case-study',
  TEACHER_TEST: '/teachers/test',
  TEACHER_EXPLANATION: '/teachers/explanation',
  TEACHER_MY_PROFILE: '/teachers/overview',
  AUTH_LOGIN: '/auth/login',
  AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
  AUTH_FORGOT_PASSWORD_RECOVER: '/auth/forgot-password/recover',
  AUTH_CHANGE_PASSWORD: '/auth/change-password',
  AUTH_CHANGE_PASSWORD_SUCCESS: '/auth/change-password/change-password-success',
  NOTIFICATION: '/notifications',
  ENTRANCE_TEST: '/entrance-test',
  MYPROFILE: '/overview',
  PAGE_NOT_FOUND: '/404',
  COURSE_DETAIL: '/courses/my-course/[courseId]',
  TEACHER_COURSE_DETAIL_ID: '/teachers/courses/my-course/[courseId]',
  COURSE_PART_DETAIL: '/courses/[id]/section/[course_section_id]',
  TEACHER_COURSE_PART_DETAIL:
    '/teachers/courses/[id]/section/[course_section_id]',
  COURSE_ACTIVITY: '/courses/[id]/activity/[activityId]',
  TEACHER_COURSE_ACTIVITY: '/teachers/courses/[id]/activity/[activityId]',
  TEST_RESULT: '/courses/test/test-result/[id]',
  USERPAGE: '/[page]',
  EVENT_TEST: '/event-test',
  RESULTS: '/courses/my-course/[courseId]/results',
  MY_CALENDAR: '/teachers/my-calendar',
  REQUEST: '/request',
  MY_REQUEST: '/teachers/my-request',
  DASHBOARD: '/courses/my-course/[courseId]/dashboard',
  COURSE_CONTENT: '/courses/my-course/[courseId]',
  CALENDAR: '/calendar',
  EXAM_LIST: '/exam_list',
  CLASS_RESOURCE: '/courses/my-course/[courseId]/class-resource',
  COURSE_ACTIVATION: '/course-activation',
}
